# Site settings
title: Personal Development
email: jonathan.d.s.pike@gmail.com
author: Jonathan Pike
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jonathanpike.net" # the base hostname & protocol for your site
twitter_username: jonathanpike
github_username:  jonathanpike
paginate: 5
timezone: America/Toronto

# Pages
pages_list:
  About: '/about/'
  Credits: '/credits/'

# Build settings
markdown: kramdown
highlighter: rouge
permalinks: pretty

# Markdown Processor
kramdown: 
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - month
  layout: archives-month
  permalinks:
    month: '/archives/:year/:month/'