# Site settings
title: Personal Development
description: by Jonathan Pike
email: jonathan.d.s.pike@gmail.com
author: Jonathan Pike
url: "http://www.jonathanpike.net"
baseurl: "" 
paginate: 5
paginate_path: "/page/:num"
timezone: America/Toronto

# SEO
twitter:
  username: jonathanpike
social:
  links: ['https://ca.linkedin.com/in/pikejonathan', 'https://twitter.com/jonathanpike', 'https://github.com/jonathanpike']


# Pages
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Resume: '/resume/'
  Projects: '/projects/'

# Build settings
markdown: kramdown
sass:
    style: compressed

# Markdown Processor
kramdown: 
  input: GFM

# Gems
gems:
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate

# Archives
permalinks: '/:year/:month/:title'

# Exclusions
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'Rakefile']