# Site settings
title: jonathanpike.net
description: Personal Development
email: jonathan.d.s.pike@gmail.com
author: Jonathan Pike
baseurl: "" 
url: "jonathanpike.net" 
paginate: 5
paginate_path: "/page/:num"
timezone: America/Toronto

# Pages
pages_list:
  About: '/about/'
  Credits: '/credits/'

# Build settings
markdown: kramdown
highlighter: rouge

# Markdown Processor
kramdown: 
  input: GFM
  syntax_highlighter: rouge

# Gems
gems:
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - month
  layout: archives-month
  permalinks:
    month: '/archives/:year/:month/'
    
# Exclusions
exclude: ['Gemfile', 'Gemfile.lock', 'config.ru', 'vendor', 'Rakefile', 'Procfile']