# Site settings
title: Jonathan Pike, software developer
description: The personal weblog of Jonathan Pike, exploring life as a software developer
email: jonathan.d.s.pike@gmail.com
author: Jonathan Pike
url: "https://www.jonathanpike.net"
paginate: 5
paginate_path: "/page/:num"
timezone: America/Toronto

# SEO
twitter:
  username: jonathanpike
social:
  links: ['https://ca.linkedin.com/in/pikejonathan', 'https://twitter.com/jonathanpike', 'https://github.com/jonathanpike']

# Build settings
markdown: kramdown
sass:
  style: compressed

# Markdown Processor
kramdown: 
  input: GFM

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate

# Archives
permalink: '/:year/:month/:title'

# Exclusions
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'Rakefile']
