# Site settings
title: jonathanpike.net
description: Personal Development
email: jonathan.d.s.pike@gmail.com
author: Jonathan Pike
baseurl: "" 
url: "jonathanpike.net" 
paginate: 5
paginate_path: "/page/:num"
timezone: America/Toronto

# Pages
pages_list:
  About: '/about/'
  Credits: '/credits/'

# Build settings
markdown: kramdown
# highlighter: rouge
sass:
    style: compressed

# Markdown Processor
kramdown: 
  input: GFM
  # syntax_highlighter: rouge

# Gems
gems:
  - jekyll-archives
  - jekyll-redirect-from

# Archives
permalinks: '/:year/:month/:title'

# Exclusions
exclude: ['Gemfile', 'Gemfile.lock', 'config.ru', 'vendor', 'Rakefile', 'Procfile']